/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_pax_jni_PaxNative */

#ifndef _Included_com_pax_kernel_logger_PaxNative
#define _Included_com_pax_kernel_logger_PaxNative
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_pax_jni_PaxNative
 * Method:    getBuildTime
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_pax_kernel_logger_LoggerController_getLogString
  (JNIEnv *, jobject);

JNIEXPORT void Java_com_pax_kernel_logger_LoggerController_loadKernelLog
  (JNIEnv* , jobject , jstring , jint );

#ifdef __cplusplus
}
#endif
#endif
